### ISSUE TITLE
Single Channel Mode and Sustain

### ISSUE THREAD

**Issue by mheidt** [zynthian/zyncoder#14]
I am running in Single Channel Mode and have a Pianoteq layer on channel 1 and a zynaddsubfx on channel2.

When I hold the sustain pedal and switch from Pianoteq to zynaddsubfx, the sound is held like expected.
But when I release the sustain pedal, the sound doesn't mute, which I like to see.

When I am on channel 2 on the zynaddsubfx holding the sustain pedal and switch back to channel 1, the sound mutes, which i wouldn't suspect.

**Comment by jofemodo** [comment]
Now it's solved. I've added a mechanism that manage gracefully sustained notes and sustain pedal across active channel changes. Please, @mheidt and others, test it carefully and tell me if you find some problem.
