### ISSUE TITLE
add MIDI Filter/Routing based on Port

### ISSUE THREAD

**Issue by orcascc** [zynthian/zyncoder#26]
Hy,

please add the possibility to filter/route midi based an the port the data came from.

as an example: I have two Keyboards, both sending on MIDI Channel 1, but they are connected via extra USB-MIDI cables (or direct via USB). With the port based filter/router I could change the MIDI Channel from a keyboard to another channel or filter data from a Keyboard.

Thanks, Andy

**Comment by riban-bw** [comment]
The OP has keyboards that cannot have their MIDI channel changed unfortunately.

Such a feature would need to enumerate all USB MIDI devices and allow rules for each. This enumeration may change depending on various factors resulting in different results. It is possible to enumerate using USB hub and port indices which probably offers the most consistent user experience in this case where the same keyboard tour is being used though some users may expect unique keyboard types to always behave the same no matter where they are plugged!

This is a niche requirement that requires some consideration and effort so is likely to be a low priority deliverable, i.e. someone is going to want the challenge 😀 ... and have the time.

**Comment by Pastitas** [comment]
This feature could also allow for MPE device filtering, so i will try to find time to look into it

**Comment by riban-bw** [comment]
Device based MIDI routing is now implemented.
