### ISSUE TITLE
Pitchwheel controller sent after each note MIDI note on

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zyncoder#27]
**Describe the bug**
ZynMidiRouter seems to send a pitchwheel message after every MIDI note on message.

**To Reproduce**
1. Navigate to [MIDI log](http://zynthian.local/ui-midi-log) within webconf
2. Play a MIDI note

**Expected behaviour**
The MIDI note message is displayed.

**Actual behaviour**
The MIDI note message is displayed followed by CH#01 PITCHWHEEL 0

**Setup:**
Raspberry Pi 4 Model B Rev 1.2
Soundcard: HifiBerry DAC+ light
Display: WaveShare 7 HDMI+GPIO 1024x600
Wiring: I2C_HWC
GPIO Expander: Not detected

Raspbian GNU/Linux 10 (buster)
Build Date: 2020-03-28

zyncoder: i2c_longpress (40725eb)
zynthian-ui: master (f2d6ea6)
zynthian-sys: master (a305ab9)
zynthian-data: master (9cccef5)
zynthian-webconf: master (d72a695)

**Comment by jofemodo** [comment]
Hi @riban-bw !
I removed the spurious PB0 messages when zynthian is tuned to 440Hz. Please, update and test.
