### ISSUE TITLE
Failure of startup when zynaptik selected.

### ISSUE THREAD

**Issue by wyleu** [zynthian/zyncoder#31]
**Describe the bug**
After selecting any zynaptik option the machine start up fails

**To Reproduce**
1. Go to wiring
2. Click on any zynaptik option
3. Reboot

**Expected behavior**
Expect zynaptik to function and zynth to start

**Screenshots**
ON start up 

Jan 28 21:20:15 zynthian-pedal startx[6994]: libjackpeak created input ports
Jan 28 21:20:15 zynthian-pedal startx[6994]: ERROR:zynthian_gui.__init__: ERROR initializing Controllers & MIDI-router: 'NoneType' object has no attribute 'setup_zynswitch_midi'

Upon attempting to run build.sh ...

![image](https://user-images.githubusercontent.com/79083/106201541-834e0980-61b0-11eb-84d9-0ea4c5cc5878.png)

**Setup:**
 - SD-image
 - Hardware Config
 - Software Version
![image](https://user-images.githubusercontent.com/79083/106201781-de7ffc00-61b0-11eb-88b3-6af48058cbfa.png)

**Additional context**

**Comment by jofemodo** [comment]
I fixed this issue on dcb627e4b65d353b5e170f002ff453eaa62b81c3.
You don't need to lie about your wiring hardware and can use "dummies". Unfortunately, it still don't work with v1 (MCP23008) or configuration with encoders directly connected to RBPi.
