### ISSUE TITLE
Have to remove layer to change pianoteq preset

### ISSUE THREAD

**Issue by hal80** [zynthian/zyncoder#33]
**Describe the bug**
If one wants to change the pianoteq preset of an instrument, it’s not possible to just scroll through the preset list and press select:  the heading changes but the preset remains the same as before. 

**To Reproduce**
1. Boot zynthian, no engines loaded
2. Chose “new synth layer” → “Pianoteq 7.2 STANDARD” → “MIDI Ch#1” → Instrument → Preset. This loads okay.
3. Now try to change preset: Press back encoder in order to display the preset list for that instrument.
4. Scroll to another preset and (1) either wait (if "[x] preset preload" in admin menu) or (2) press select encoder to chose (if "[ ] preset preload" in admin menu). Zynthian tries to load something, heading changes to the selected preset, but the bug is, that the chosen preset is actually not loaded. Instead, the previously selected preset remains active which can be noticed by playing some notes.

Fallback solution is to completely remove the layer, and then start all over again, i.e. from the menu, chose “new synth layer” → “Pianoteq 7.2 STANDARD” → “MIDI Ch#1” and so on.

The option “[ ] Preset Preload” has no effect on the observed bug.

**Expected behavior**
chosen preset loads upon clicking select encoder in step 4.

**Setup:**
HARDWARE
Raspberry Pi 4 Model B Rev 1.1
Soundcard: HifiBerry DAC+ ADC
Display: PiScreen 3.5 (v2)
Wiring: MCP23017_ENCODERS
GPIO Expander: MCP23017

SOFTWARE
zyncoder: master (3c914fe)
zynthian-ui: master (84a7f25)
zynthian-sys: master (348f40c)
zynthian-data: master (194fd59)
zynthian-webconf: master (c8cd1a6)

SYSTEM
Raspbian GNU/Linux 10 (buster)
Build Date: 2020-09-05
Memory: 17% (332M/1939M)
SD Card: 34% (9.4G/29G)

**Comment by jofemodo** [comment]
Bug introduced when trying to solve https://github.com/zynthian/zyncoder/issues/32. Fixed by https://github.com/zynthian/zyncoder/issues/32 and https://github.com/zynthian/zyncoder/issues/32.
