### ISSUE TITLE
SYSRT Clock is always routed when "Route MIDI to Output Ports" is enabled

### ISSUE THREAD

**Issue by mark-orion** [zynthian/zyncoder#36]
**Describe the bug**
Whenever I enable the "Route MIDI to Output Ports" option in the web-ui, MIDI system realtime clock messages are always routed, regardless if "Enable System Messages (Transport)" is enabled or not.

**Expected behavior**
When "Route MIDI to Output Ports"  is enabled, no system messages should get through unless the option is enabled too.

**Comment by jofemodo** [comment]
Hi @mark-orion !!

I solved this. Please, update and test (testing branch, of course).

Thanks,
